<?php

 $title = 'Телефонный справочник';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php if ($this->isAllowed('controller/Blog\Controller\Write:add', 'admin')) { ?>
 <p>
     <a href="<?php echo $this->url('phone', array('action'=>'add'));?>">Добавить новую запись</a>
 </p>
<?php } ?>

 <table class="table table-bordered table-hover table-striped">
 <tr>
     <th>Должность</th>
     <th>ФИО</th>
     <th>Должность</th>
     <th>Офис</th>
     <th>Тел. внутр</th>
     <th>Тел. городской</th>
     <th>Сотовый</th>
     <th>E-mail</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($albums as $album) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($album->title);?></td>
     <td><?php echo $this->escapeHtml($album->artist);?></td>
     <td>
         <a href="<?php echo $this->url('phone',
             array('action'=>'edit', 'id' => $phone->id));?>">Edit</a>
         <a href="<?php echo $this->url('phone',
             array('action'=>'delete', 'id' => $phone->id));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>
