<?php
// Generated by Zend Framework 2
return array(
    'Budget\Controller\BDDSController' => __DIR__ . '/module/Budget/src/Budget/Controller/BDDSController.php',
    'Budget\Module'                    => __DIR__ . '/module/Budget/Module.php',
);