<?php
// Generated by Zend Framework 2
return array(
//    'Application\Controller\IndexController' => __DIR__ . '/module/Application/src/Application/Controller/IndexController.php',
//    'Application\Module'                     => __DIR__ . '/module/Application/Module.php',
    'Report\Controller\ReportController'     => __DIR__ . '/module/Report/src/Report/Controller/ReportController.php',
    'Report\Module'                         => __DIR__ . '/module/Report/Module.php',
);