<?php
// Generated by Zend Framework 2
return array(
    'Doc\Controller\DocController' => __DIR__ . '/src/Doc/Controller/DocController.php',
    'Doc\Module'                   => __DIR__ . '/Module.php',
);