<?php
// Generated by Zend Framework 2
return array(
    'Partner\Controller\PartnerController' => __DIR__ . '/module/Partner/src/Partner/Controller/PartnerController.php',
    'Partner\Module'                       => __DIR__ . '/module/Partner/Module.php',
);