<h1>Мои записи</h1>
<a href="<?php echo $this->url('post/add');?>"><?php echo $this->translate('Add new blog'); ?></a>
<?php foreach ($this->posts as $post): ?>
    <article>
        <h1 id="post<?php echo $post->getId() ?>"><?php echo $post->getTitle() ?></h1>
        <p>
               <?php echo $post->getText() ?>
        </p>
                
	<a href="<?php echo $this->url('post') ?>/<?php echo $post->getid() ?>">Подробнее</a>
     
     </article>
<?php endforeach ?>