<?php
// Generated by Zend Framework 2
return array(
    'Admin\Controller\AdminController' => __DIR__ . '/src/Admin/Controller/AdminController.php',
    'Admin\Module'                     => __DIR__ . '/Module.php',
);