<!-- Filename: /module/Blog/view/blog/list/index.phtml -->
<h1>Мои записи</h1>

<?php foreach ($this->posts as $post): ?>
    <article>
        <h1 id="post<?php echo $post->getId() ?>"><?php echo $post->getTitle() ?></h1>
        <p>
               <?php echo $post->getText() ?>
        </p>
                
	<a href="<?php echo $this->url('post') ?>/<?php echo $post->getid() ?>">Подробнее</a>
     
     </article>
<?php endforeach ?>