<?php
// Generated by Zend Framework 2
return array(
    'TMC\Controller\TMCController' => __DIR__ . '/src/TMC/Controller/TMCController.php',
    'TMC\Module'                   => __DIR__ . '/Module.php',
);