<?php
// Generated by Zend Framework 2
return array(
    'Purchase\Controller\PurchaseController' => __DIR__ . '/module/Purchase/src/Purchase/Controller/PurchaseController.php',
    'Purchase\Module'                        => __DIR__ . '/module/Purchase/Module.php',
);