 <?php
 $title = 'Delete task';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <p>Are you sure that you want to delete the
   '<?php echo $this->escapeHtml($task->getTitle()); ?>' task?
 </p>
 <?php
 $url = $this->url('task', array('action' => 'delete', 'id'=>$id)); ?>
 <form action="<?php echo $url; ?>" method="post">
 
 <div class = "form-group">
   <input class='btn btn-danger' type="submit" name="del" value="Yes" />
   <input class='btn btn-primary' type="submit" name="del" value="No" />
 </div>
 </form>

