<!-- Filename: /module/Blog/view/blog/delete/delete.phtml -->
<h1>DeleteController::deleteAction()</h1>
<p>
     Are you sure that you want to delete
     '<?php echo $this->escapeHtml($this->post->getTitle()); ?>' by
     '<?php echo $this->escapeHtml($this->post->getText()); ?>'?
 </p>
<form action="<?php echo $this->url('post', array(), true) ?>" method="post">
     <input type="hidden" name="id" value="<?php echo $post->getId(); ?>">
     <input class = "btn btn-danger" type="submit" name="delete_confirmation" value="yes">
     <input class = "btn btn-primary" type="submit" name="delete_confirmation" value="no">
</form>
