<?php
// Generated by Zend Framework 2
return array(
    'Software\Controller\SoftwareController' => __DIR__ . '/src/Software/Controller/SoftwareController.php',
    'Software\Module'                        => __DIR__ . '/Module.php',
);